title: "Part 3: Year 8 'Relevance' training – Investigating App Lab"
hero_image: images/banner2.png
description: Part 3 of the online training course introduces teachers to the second part of the resources for the Year 8 Relevance trial through a series of tasks (focusing on App Lab)
version: 4
listed: false
copyedit: false
last_tested: "2020-09-08"
steps:
  - title: "Task 1: Technical setup for trial"
  - title: "Task 2: Program in App Lab"
  - title: "Task 3: Build your app"
  - title: "Task 4: User testing"
  - title: "Task 5: Completion survey"
